import type { Product, HeroSlide, Category, CategorySlug } from '@/types';

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: '1',
    title: 'Steam Summer Sale',
    subtitle: 'Giảm đến 80% hàng ngàn tựa game bom tấn',
    image: '/images/hero-steam.jpg',
    ctaText: 'Xem ngay',
    ctaLink: '/search?category=game-keys',
    badge: 'HOT DEAL',
  },
  {
    id: '2',
    title: 'Netflix Premium 1 Năm',
    subtitle: 'Giá chỉ từ 199K — Xem phim không giới hạn',
    image: '/images/hero-netflix.jpg',
    ctaText: 'Mua ngay',
    ctaLink: '/products/netflix-premium-1-year',
    badge: 'BEST SELLER',
  },
  {
    id: '3',
    title: 'ChatGPT Plus Lifetime',
    subtitle: 'Trải nghiệm AI mạnh nhất — Giá ưu đãi nhất',
    image: '/images/hero-chatgpt.jpg',
    ctaText: 'Khám phá',
    ctaLink: '/products/chatgpt-plus-lifetime',
  },
];

export const CATEGORIES_DATA: Category[] = [
  { slug: 'all', label: 'Tất cả', icon: 'Grid3X3', count: 24 },
  { slug: 'game-keys', label: 'Game Keys', icon: 'Gamepad2', count: 12 },
  { slug: 'streaming', label: 'Streaming', icon: 'Play', count: 6 },
  { slug: 'productivity', label: 'Productivity', icon: 'Briefcase', count: 4 },
  { slug: 'ai-tools', label: 'AI Tools', icon: 'Sparkles', count: 2 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'elden-ring-steam-key',
    name: 'Elden Ring',
    type: 'game-key',
    platform: 'steam',
    category: 'game-keys',
    price: 450000,
    originalPrice: 990000,
    discount: 55,
    thumbnail: '/images/products/elden-ring.jpg',
    images: ['/images/products/elden-ring.jpg', '/images/products/elden-ring-2.jpg'],
    description: 'Elden Ring là một tựa game nhập vai hành động thế giới mở được phát triển bởi FromSoftware. Khám phá thế giới Lands Between rộng lớn với chiến đấu đầy thử thách và câu chuyện sâu sắc do Hidetaka Miyazaki và George R.R. Martin đồng sáng tạo.',
    shortDescription: 'Game nhập vai hành động thế giới mở — FromSoftware',
    deliveryType: 'instant',
    stock: 45,
    maxStock: 100,
    tags: ['rpg', 'action', 'open-world', 'souls-like'],
    featured: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    slug: 'cyberpunk-2077-steam-key',
    name: 'Cyberpunk 2077',
    type: 'game-key',
    platform: 'steam',
    category: 'game-keys',
    price: 350000,
    originalPrice: 599000,
    discount: 42,
    thumbnail: '/images/products/cyberpunk.jpg',
    images: ['/images/products/cyberpunk.jpg'],
    description: 'Cyberpunk 2077 là game nhập vai thế giới mở lấy bối cảnh Night City — một thành phố đầy quyền lực, sự quyến rũ và cải tạo cơ thể. Bạn vào vai V, một lính đánh thuê ngoài vòng pháp luật.',
    shortDescription: 'RPG thế giới mở — CD Projekt Red',
    deliveryType: 'instant',
    stock: 30,
    maxStock: 100,
    tags: ['rpg', 'action', 'open-world', 'cyberpunk'],
    featured: true,
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    slug: 'rdr2-steam-key',
    name: 'Red Dead Redemption 2',
    type: 'game-key',
    platform: 'steam',
    category: 'game-keys',
    price: 299000,
    originalPrice: 790000,
    discount: 62,
    thumbnail: '/images/products/rdr2.jpg',
    images: ['/images/products/rdr2.jpg'],
    description: 'Red Dead Redemption 2 mang đến một thế giới rộng lớn, sống động ở miền Tây nước Mỹ năm 1899. Câu chuyện của Arthur Morgan, một kẻ ngoài vòng pháp luật trong băng Van der Linde.',
    shortDescription: 'Open-world Western — Rockstar Games',
    deliveryType: 'instant',
    stock: 8,
    maxStock: 50,
    tags: ['action', 'adventure', 'open-world', 'western'],
    flashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: '2024-03-05',
  },
  {
    id: '4',
    slug: 'god-of-war-ragnarok-steam',
    name: 'God of War Ragnarök',
    type: 'game-key',
    platform: 'steam',
    category: 'game-keys',
    price: 550000,
    originalPrice: 1190000,
    discount: 54,
    thumbnail: '/images/products/gow-ragnarok.jpg',
    images: ['/images/products/gow-ragnarok.jpg'],
    description: 'Kratos và Atreus phải du hành đến mỗi trong Chín Thế giới để tìm kiếm câu trả lời khi lực lượng Asgard chuẩn bị cho trận chiến cuối cùng.',
    shortDescription: 'Action-Adventure — Santa Monica Studio',
    deliveryType: 'instant',
    stock: 22,
    maxStock: 80,
    tags: ['action', 'adventure', 'mythology'],
    featured: true,
    flashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    createdAt: '2024-04-01',
  },
  {
    id: '5',
    slug: 'gta-v-epic-key',
    name: 'Grand Theft Auto V',
    type: 'game-key',
    platform: 'epic',
    category: 'game-keys',
    price: 199000,
    originalPrice: 459000,
    discount: 57,
    thumbnail: '/images/products/gta5.jpg',
    images: ['/images/products/gta5.jpg'],
    description: 'Grand Theft Auto V cho PC cung cấp cho người chơi cơ hội khám phá thế giới rộng lớn và chi tiết của Los Santos và Blaine County.',
    shortDescription: 'Open-world Action — Rockstar Games',
    deliveryType: 'instant',
    stock: 120,
    maxStock: 200,
    tags: ['action', 'open-world', 'multiplayer'],
    createdAt: '2024-01-20',
  },
  {
    id: '6',
    slug: 'netflix-premium-1-year',
    name: 'Netflix Premium 1 Năm',
    type: 'account',
    platform: 'netflix',
    category: 'streaming',
    price: 199000,
    originalPrice: 399000,
    discount: 50,
    thumbnail: '/images/products/netflix.jpg',
    images: ['/images/products/netflix.jpg'],
    description: 'Tài khoản Netflix Premium sử dụng trong 12 tháng. Xem phim, series không giới hạn trên 4 thiết bị cùng lúc với chất lượng Ultra HD 4K.',
    shortDescription: 'Tài khoản Premium 12 tháng — 4K Ultra HD',
    deliveryType: 'manual',
    stock: 50,
    maxStock: 100,
    tags: ['streaming', 'movie', '4k'],
    featured: true,
    createdAt: '2024-02-15',
  },
  {
    id: '7',
    slug: 'spotify-premium-6-months',
    name: 'Spotify Premium 6 Tháng',
    type: 'account',
    platform: 'spotify',
    category: 'streaming',
    price: 99000,
    originalPrice: 179000,
    discount: 45,
    thumbnail: '/images/products/spotify.jpg',
    images: ['/images/products/spotify.jpg'],
    description: 'Tài khoản Spotify Premium 6 tháng. Nghe nhạc không quảng cáo, tải về nghe offline, chất lượng âm thanh cao.',
    shortDescription: 'Premium 6 tháng — Nghe nhạc không quảng cáo',
    deliveryType: 'manual',
    stock: 35,
    maxStock: 80,
    tags: ['music', 'streaming', 'premium'],
    createdAt: '2024-03-10',
  },
  {
    id: '8',
    slug: 'chatgpt-plus-lifetime',
    name: 'ChatGPT Plus Lifetime',
    type: 'account',
    platform: 'chatgpt',
    category: 'ai-tools',
    price: 499000,
    originalPrice: 1200000,
    discount: 58,
    thumbnail: '/images/products/chatgpt.jpg',
    images: ['/images/products/chatgpt.jpg'],
    description: 'Tài khoản ChatGPT Plus vĩnh viễn. Truy cập GPT-4, tạo hình ảnh với DALL-E, phân tích dữ liệu nâng cao và nhiều tính năng Premium khác.',
    shortDescription: 'Tài khoản Plus vĩnh viễn — GPT-4 & DALL-E',
    deliveryType: 'manual',
    stock: 15,
    maxStock: 30,
    tags: ['ai', 'chatbot', 'premium'],
    featured: true,
    flashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    createdAt: '2024-04-20',
  },
  {
    id: '9',
    slug: 'canva-pro-1-year',
    name: 'Canva Pro 1 Năm',
    type: 'account',
    platform: 'canva',
    category: 'productivity',
    price: 149000,
    originalPrice: 299000,
    discount: 50,
    thumbnail: '/images/products/canva.jpg',
    images: ['/images/products/canva.jpg'],
    description: 'Tài khoản Canva Pro 12 tháng. Truy cập hàng triệu template, ảnh stock, công cụ AI xóa phông, resize tự động và nhiều tính năng chuyên nghiệp.',
    shortDescription: 'Pro 12 tháng — Template & AI tools không giới hạn',
    deliveryType: 'manual',
    stock: 40,
    maxStock: 100,
    tags: ['design', 'productivity', 'ai'],
    createdAt: '2024-03-25',
  },
  {
    id: '10',
    slug: 'hogwarts-legacy-steam',
    name: 'Hogwarts Legacy',
    type: 'game-key',
    platform: 'steam',
    category: 'game-keys',
    price: 399000,
    originalPrice: 890000,
    discount: 55,
    thumbnail: '/images/products/hogwarts.jpg',
    images: ['/images/products/hogwarts.jpg'],
    description: 'Hogwarts Legacy là game nhập vai thế giới mở lấy bối cảnh thế kỷ 19 của thế giới phù thủy Harry Potter. Khám phá Hogwarts, học phép thuật và viết nên câu chuyện của riêng bạn.',
    shortDescription: 'Open-world RPG — Wizarding World',
    deliveryType: 'instant',
    stock: 55,
    maxStock: 100,
    tags: ['rpg', 'open-world', 'magic', 'adventure'],
    flashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
    createdAt: '2024-02-28',
  },
  {
    id: '11',
    slug: 'adobe-creative-cloud-1-year',
    name: 'Adobe Creative Cloud 1 Năm',
    type: 'account',
    platform: 'adobe',
    category: 'productivity',
    price: 699000,
    originalPrice: 1599000,
    discount: 56,
    thumbnail: '/images/products/adobe.jpg',
    images: ['/images/products/adobe.jpg'],
    description: 'Tài khoản Adobe Creative Cloud 12 tháng. Truy cập toàn bộ ứng dụng: Photoshop, Illustrator, Premiere Pro, After Effects và hơn 20 ứng dụng khác.',
    shortDescription: 'Full Apps 12 tháng — Photoshop, Premiere Pro...',
    deliveryType: 'manual',
    stock: 20,
    maxStock: 50,
    tags: ['design', 'video', 'productivity', 'creative'],
    createdAt: '2024-04-15',
  },
  {
    id: '12',
    slug: 'starfield-xbox-key',
    name: 'Starfield',
    type: 'game-key',
    platform: 'xbox',
    category: 'game-keys',
    price: 499000,
    originalPrice: 1290000,
    discount: 61,
    thumbnail: '/images/products/starfield.jpg',
    images: ['/images/products/starfield.jpg'],
    description: 'Starfield là RPG vũ trụ thế hệ mới từ Bethesda Game Studios. Hơn 1.000 hành tinh để khám phá, xây dựng tàu vũ trụ và viết nên câu chuyện riêng trong không gian.',
    shortDescription: 'Space RPG — Bethesda Game Studios',
    deliveryType: 'instant',
    stock: 18,
    maxStock: 60,
    tags: ['rpg', 'space', 'open-world', 'sci-fi'],
    createdAt: '2024-05-01',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return MOCK_PRODUCTS.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return MOCK_PRODUCTS.filter((p) => p.featured);
}

export function getFlashSaleProducts(): Product[] {
  return MOCK_PRODUCTS.filter((p) => p.flashSale);
}

export function getProductsByCategory(category: CategorySlug): Product[] {
  if (category === 'all') return MOCK_PRODUCTS;
  return MOCK_PRODUCTS.filter((p) => p.category === category);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return MOCK_PRODUCTS
    .filter((p) => p.id !== product.id && (p.category === product.category || p.platform === product.platform))
    .slice(0, limit);
}
